const { createCanvas, registerFont } = require('canvas');
const fs = require('fs');
const path = require('path');

// Font sizes to generate: width x height
const FONT_SIZES = [
  { width: 12, height: 16 },
  { width: 16, height: 24 },
  { width: 24, height: 36 },
  { width: 32, height: 48 },
  { width: 48, height: 54 }
];

// Font weight (normal, bold, etc.)
const FONT_WEIGHT = '600';

// ASCII character range (32-127)
const CHAR_START = 32;
const CHAR_END = 127;
const CHAR_COUNT = CHAR_END - CHAR_START + 1;

function generateBitmapFont(fontPath, fontSize) {
  const { width, height } = fontSize;

  // Register the font
  registerFont(fontPath, { family: 'CustomFont' });

  // Create canvas
  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext('2d');

  // Set font properties
  ctx.font = `${FONT_WEIGHT} ${height}px CustomFont`;
  ctx.fillStyle = 'white';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';

  const bitmapData = [];

  for (let charCode = CHAR_START; charCode <= CHAR_END; charCode++) {
    // Clear canvas
    ctx.clearRect(0, 0, width, height);

    // Draw character
    const char = String.fromCharCode(charCode);
    ctx.fillText(char, width / 2 + 1, height / 2);

    // Get image data
    const imageData = ctx.getImageData(0, 0, width, height);
    const pixels = imageData.data;

    // Convert to bitmap (row by row, 8 pixels per byte)
    const charBitmap = [];
    const bytesPerRow = Math.ceil(width / 8);

    for (let y = 0; y < height; y++) {
      for (let byteX = 0; byteX < bytesPerRow; byteX++) {
        let byte = 0;

        for (let bit = 0; bit < 8; bit++) {
          const x = byteX * 8 + bit;
          if (x < width) {
            const pixelIndex = (y * width + x) * 4;
            // Check alpha channel (pixels are white on transparent)
            const alpha = pixels[pixelIndex + 3];
            if (alpha > 64) {
              byte |= (1 << (7 - bit));
            }
          }
        }

        charBitmap.push(byte);
      }
    }

    bitmapData.push(charBitmap);
  }

  return bitmapData;
}

function generateCFile(fontName, fontSize, bitmapData) {
  const { width, height } = fontSize;
  const bytesPerChar = Math.ceil(width / 8) * height;
  const totalBytes = bytesPerChar * CHAR_COUNT;

  let cCode = `#include <stdint.h>\n\n`;
  cCode += `// ${fontName}_${width}x${height}.c\n`;
  cCode += `// Font type    : Full (${CHAR_COUNT} characters)\n`;
  cCode += `// Font size    : ${width}x${height} pixels\n`;
  cCode += `// Generated by ChipNomad bitmap font generator\n\n`;
  cCode += `uint8_t font${width}x${height}[${totalBytes}] = {\n`;

  for (let charIndex = 0; charIndex < CHAR_COUNT; charIndex++) {
    const charCode = CHAR_START + charIndex;
    const char = String.fromCharCode(charCode);
    const charName = getCharName(char);

    const charData = bitmapData[charIndex];
    const hexBytes = charData.map(byte => `0x${byte.toString(16).padStart(2, '0').toUpperCase()}`);

    cCode += hexBytes.join(',') + `,  // ${charName}\n`;
  }

  cCode += `};\n`;

  return cCode;
}

function getCharName(char) {
  const charCode = char.charCodeAt(0);

  if (charCode === 32) return '<space>';
  if (charCode === 92) return '<backslash>';
  if (charCode >= 33 && charCode <= 126) return char;

  return `<${charCode}>`;
}

function main() {
  const args = process.argv.slice(2);

  if (args.length < 1) {
    console.log('Usage: node generate.js <font-file.ttf> [output-dir]');
    console.log('');
    console.log('Generates bitmap fonts in the following sizes:');
    FONT_SIZES.forEach(size => {
      console.log(`  ${size.width}x${size.height} pixels`);
    });
    process.exit(1);
  }

  const fontPath = args[0];
  const outputDir = args[1] || './output';

  if (!fs.existsSync(fontPath)) {
    console.error(`Font file not found: ${fontPath}`);
    process.exit(1);
  }

  // Create output directory
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const fontName = path.basename(fontPath, path.extname(fontPath));

  console.log(`Generating bitmap fonts from: ${fontPath}`);
  console.log(`Output directory: ${outputDir}`);
  console.log('');

  FONT_SIZES.forEach(fontSize => {
    console.log(`Generating ${fontSize.width}x${fontSize.height}...`);

    try {
      const bitmapData = generateBitmapFont(fontPath, fontSize);
      const cCode = generateCFile(fontName, fontSize, bitmapData);

      const outputFile = path.join(outputDir, `font_${fontSize.width}x${fontSize.height}.c`);
      fs.writeFileSync(outputFile, cCode);

      console.log(`  Generated: ${outputFile}`);
    } catch (error) {
      console.error(`  Error generating ${fontSize.width}x${fontSize.height}: ${error.message}`);
    }
  });

  console.log('\\nDone!');
}

if (require.main === module) {
  main();
}